version: 2.0

jobs:
  prepare:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/polylith
    steps:
      - checkout
      - attach_workspace:
          at: ~/polylith
      - restore_cache:
          key: lein-polylith-{{ checksum "project.clj" }}
      - run:
          name: install into local repo
          command: lein install
      - save_cache:
          key: lein-polylith-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
            - ~/.lein
      - persist_to_workspace:
          root: .
          paths: 
            - .

  test:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/polylith
    steps:
      - attach_workspace:
          at: ~/polylith
      - restore_cache:
          key: lein-polylith-{{ checksum "project.clj" }}
      - run:
          name: Add global git user email
          command: git config --global user.email "test@test.com"
      - run:
          name: Add global git user name
          command: git config --global user.name "CircleCI"
      - run:
          name: test
          command: lein test

  deploy:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/polylith
    steps:
      - attach_workspace:
          at: ~/polylith
      - restore_cache:
          key: lein-polylith-{{ checksum "project.clj" }}
      - run:
          name: deploy to clojars
          command: lein deploy clojars

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
