(ns leiningen.polylith.cmd.help.changes)

(defn help [sha1 sha2]
  (println "  Show what has changed between two Git hashes.")
  (println "")
  (println "  lein polylith changes x s1 s2")
  (println "    x = i[nterface] -> show changed interfaces")
  (println "        c[omponent] -> show changed components")
  (println "        b[ase]      -> show changed bases")
  (println "        s[ystem]    -> show changed systems")
  (println "    s1 = last (successful) Git sha1")
  (println "    s2 = current Git sha1")
  (println)
  (println "  example:")
  (println "    lein polylith changes i" sha1 sha2)
  (println "    lein polylith changes c" sha1 sha2)
  (println "    lein polylith changes component" sha1 sha2)
  (println "    lein polylith changes b" sha1 sha2)
  (println "    lein polylith changes s" sha1 sha2))

