(ns leiningen.polylith.cmd.help.create)

;; todo: följ samma mönster som från changes!
(defn help []
  (println "  Create a component.")
  (println)
  (println "  lein polylith create c[omponent] NAME")
  (println "    NAME = Component name")
  (println)
  (println "  Create a workspace.")
  (println)
  (println "  lein polylith create w[orkspace] WS NS [TOP-NS]")
  (println "    WS = Workspace name")
  (println "    NS = Namespace")
  (println "    TOP-NS = If left out, it will be sett to the corresponding value of")
  (println "             the NS e.g. 'com/my/company' if NS is 'com.my.company'.")
  (println "             Set to blank if if package name only exists in the system project.clj")
  (println "             files but not as a package structure under src, e.g.:")
  (println "               (defproject com.my.comp/development \"1.0\"")
  (println "                  ...)")
  (println)
  (println "  example:")
  (println "    lein polylith create c mycomponent")
  (println "    lein polylith create component mycomp")
  (println "    lein polylith create w myworkspace com.my.company")
  (println "    lein polylith create w myworkspace com.my.company \"\""))
