(ns leiningen.polylith.cmd.help.diff)

(defn help []
  (println "  List all files and directories that has been changed since a specific point in time.")
  (println "  The file time.edn on the workspace root is excluded.")
  (println)
  (println "  lein polylith diff [ARG]")
  (println "    ARG = (omitted) -> Since last successful build, stored in bookmark")
  (println "                       :last-successful-build in WS-ROOT/time.edn.")
  (println "          timestamp -> Since the given timestamp (milliseconds since 1970).")
  (println "          bookmark  -> Since the timestamp for the given bookmark in WS-ROOT/time.edn.")
  (println "          +         -> Show time information.")
  (println)
  (println "   'lein polylith diff 0' can be used to list all files in the workspace.")
  (println)
  (println "  example:")
  (println "    lein polylith diff")
  (println "    lein polylith diff +")
  (println "    lein polylith diff + 1523649477000")
  (println "    lein polylith diff 1523649477000")
  (println "    lein polylith diff 1523649477000 +")
  (println "    lein polylith diff mybookmark"))
