(ns leiningen.polylith.cmd.help.info)

(defn help [sha1 sha2]
  (println "  Show the content of a Polylith workspace and its changes if Git hashes are given")
  (println "  (each row is followed by an * if something is changed).")
  (println)
  (println "  lein polylith info [FILTER] [HASH1 HASH2]")
  (println "    FILTER = a[ll]       -> Show all interfaces, components, bases and systems")
  (println "             c[hanged]   -> Show changed interfaces, components, bases and systems")
  (println "             u[nchanged] -> Show unchanged interfaces, components, bases and systems")
  (println "             (omitted)   -> Show all components, bases, systems (and interfaces if changed)")
  (println "    HASH1 = Last (successful) Git sha1")
  (println "    HASH2 = Current Git sha1")
  (println)
  (println "  example:")
  (println "    lein polylith info")
  (println "    lein polylith info a")
  (println "    lein polylith info all")
  (println "    lein polylith info" sha1 sha2)
  (println "    lein polylith info a" sha1 sha2)
  (println "    lein polylith info c" sha1 sha2))

