(ns leiningen.polylith.cmd.help.test)

(defn help [sha1 sha2]
  (println "  Execute or show tests.")
  (println)
  (println "  lein polylith test [OPTS] [HASH1 HASH2]")
  (println "    OPTS = (omitted) -> Execute tests")
  (println "           -         -> Print Leiningen test statement")
  (println "           +         -> Print unit tests")
  (println)
  (println "    HASH1 = Last (successful) Git sha1")
  (println "    HASH2 = Current Git sha1")
  (println)
  (println "    If HASH1 and HASH2 are given:")
  (println "      include tests from changed components and bases")
  (println "    If HASH1 and HASH2 are omitted:")
  (println "      include tests from all components and bases")
  (println)
  (println "    Tests can also be ignored, see the 'project' help.")
  (println)
  (println "  examples:")
  (println "    lein polylith test")
  (println "    lein polylith test -")
  (println "    lein polylith test +" sha1 sha2))
