(ns leiningen.polylith.cmd.help.test)

(defn help [sha1 sha2]
  (println "  Execute or show tests")
  (println)
  (println "  lein polylith test x [s1 s2]")
  (println "    x = u  -> execute unit tests")
  (println "        u- -> print Leiningen test statement")
  (println "        u+ -> print unit tests")
  (println)
  (println "    s1: last (successful) Git sha1")
  (println "    s2: current Git sha1")
  (println)
  (println "    if s1 and s2 are given:")
  (println "      include tests from changed components and bases")
  (println "    if s1 and s2 are omitted:")
  (println "      include tests from all components and bases")
  (println)
  (println "    Tests can also be ignored, see the 'project' help.")
  (println)
  (println "  examples:")
  (println "    lein polylith test u")
  (println "    lein polylith test u-")
  (println "    lein polylith test u+" sha1 sha2))
