(ns leiningen.polylith.cmd.remove-from-test
  (:require [clojure.test :refer :all]
            [leiningen.polylith.cmd.test-helper :as helper]
            [leiningen.polylith.file :as file]
            [leiningen.polylith :as polylith]))

(use-fixtures :each helper/test-setup-and-tear-down)

(deftest polylith-remove-from--remove-component-from-system-with-namespace--component-removed
  (with-redefs [file/current-path (fn [] @helper/root-dir)]
    (let [ws-dir (str @helper/root-dir "/ws1")
          project (helper/settings ws-dir "my.company")]
      (polylith/polylith nil "create" "w" "ws1" "my.company")
      (polylith/polylith project "create" "s" "sys-1" "base-1")
      (polylith/polylith project "create" "c" "comp-1" "ifc-1")
      (polylith/polylith project "create" "c" "comp-2")
      (polylith/polylith project "add" "comp-1" "sys-1")
      (polylith/polylith project "add" "comp-2" "sys-1")
      (polylith/polylith project "remove-from" "sys-1" "comp-2")

      (is (= #{".gitignore"
               ".polylith"
               ".polylith/time.local.edn"
               "Readme.md"
               "bases"
               "bases/base-1"
               "bases/base-1/Readme.md"
               "bases/base-1/project.clj"
               "bases/base-1/resources"
               "bases/base-1/resources/.keep"
               "bases/base-1/resources/base-1"
               "bases/base-1/resources/base-1/.keep"
               "bases/base-1/src"
               "bases/base-1/src/my"
               "bases/base-1/src/my/company"
               "bases/base-1/src/my/company/base_1"
               "bases/base-1/src/my/company/base_1/core.clj"
               "bases/base-1/test"
               "bases/base-1/test/my"
               "bases/base-1/test/my/company"
               "bases/base-1/test/my/company/base_1"
               "bases/base-1/test/my/company/base_1/core_test.clj"
               "components"
               "components/comp-1"
               "components/comp-1/Readme.md"
               "components/comp-1/project.clj"
               "components/comp-1/resources"
               "components/comp-1/resources/.keep"
               "components/comp-1/resources/comp-1"
               "components/comp-1/resources/comp-1/.keep"
               "components/comp-1/src"
               "components/comp-1/src/my"
               "components/comp-1/src/my/company"
               "components/comp-1/src/my/company/comp_1"
               "components/comp-1/src/my/company/comp_1/core.clj"
               "components/comp-1/src/my/company/ifc_1"
               "components/comp-1/src/my/company/ifc_1/interface.clj"
               "components/comp-1/test"
               "components/comp-1/test/my"
               "components/comp-1/test/my/company"
               "components/comp-1/test/my/company/comp_1"
               "components/comp-1/test/my/company/comp_1/core_test.clj"
               "components/comp-2"
               "components/comp-2/Readme.md"
               "components/comp-2/project.clj"
               "components/comp-2/resources"
               "components/comp-2/resources/.keep"
               "components/comp-2/resources/comp-2"
               "components/comp-2/resources/comp-2/.keep"
               "components/comp-2/src"
               "components/comp-2/src/my"
               "components/comp-2/src/my/company"
               "components/comp-2/src/my/company/comp_2"
               "components/comp-2/src/my/company/comp_2/core.clj"
               "components/comp-2/src/my/company/comp_2/interface.clj"
               "components/comp-2/test"
               "components/comp-2/test/my"
               "components/comp-2/test/my/company"
               "components/comp-2/test/my/company/comp_2"
               "components/comp-2/test/my/company/comp_2/core_test.clj"
               "environments"
               "environments/development"
               "environments/development/docs"
               "environments/development/docs/base-1-Readme.md"
               "environments/development/docs/comp-1-Readme.md"
               "environments/development/docs/comp-2-Readme.md"
               "environments/development/docs/sys-1-Readme.md"
               "environments/development/interfaces"
               "environments/development/interfaces/my"
               "environments/development/interfaces/my/company"
               "environments/development/interfaces/my/company/comp_2"
               "environments/development/interfaces/my/company/comp_2/interface.clj"
               "environments/development/interfaces/my/company/ifc_1"
               "environments/development/interfaces/my/company/ifc_1/interface.clj"
               "environments/development/project-files"
               "environments/development/project-files/bases"
               "environments/development/project-files/bases/base-1-project.clj"
               "environments/development/project-files/components"
               "environments/development/project-files/components/comp-1-project.clj"
               "environments/development/project-files/components/comp-2-project.clj"
               "environments/development/project-files/interfaces-project.clj"
               "environments/development/project-files/systems"
               "environments/development/project-files/systems/sys-1-project.clj"
               "environments/development/project-files/workspace-project.clj"
               "environments/development/project.clj"
               "environments/development/resources"
               "environments/development/resources/.keep"
               "environments/development/resources/base-1"
               "environments/development/resources/base-1/.keep"
               "environments/development/resources/comp-1"
               "environments/development/resources/comp-1/.keep"
               "environments/development/resources/comp-2"
               "environments/development/resources/comp-2/.keep"
               "environments/development/sources"
               "environments/development/sources/src"
               "environments/development/sources/src-base-1"
               "environments/development/sources/src-base-1/my"
               "environments/development/sources/src-base-1/my/company"
               "environments/development/sources/src-base-1/my/company/base_1"
               "environments/development/sources/src-base-1/my/company/base_1/core.clj"
               "environments/development/sources/src/my"
               "environments/development/sources/src/my/company"
               "environments/development/sources/src/my/company/comp_1"
               "environments/development/sources/src/my/company/comp_1/core.clj"
               "environments/development/sources/src/my/company/comp_2"
               "environments/development/sources/src/my/company/comp_2/core.clj"
               "environments/development/sources/src/my/company/comp_2/interface.clj"
               "environments/development/sources/src/my/company/ifc_1"
               "environments/development/sources/src/my/company/ifc_1/interface.clj"
               "environments/development/tests"
               "environments/development/tests/test"
               "environments/development/tests/test-base-1"
               "environments/development/tests/test-base-1/my"
               "environments/development/tests/test-base-1/my/company"
               "environments/development/tests/test-base-1/my/company/base_1"
               "environments/development/tests/test-base-1/my/company/base_1/core_test.clj"
               "environments/development/tests/test/my"
               "environments/development/tests/test/my/company"
               "environments/development/tests/test/my/company/comp_1"
               "environments/development/tests/test/my/company/comp_1/core_test.clj"
               "environments/development/tests/test/my/company/comp_2"
               "environments/development/tests/test/my/company/comp_2/core_test.clj"
               "interfaces"
               "interfaces/project.clj"
               "interfaces/src"
               "interfaces/src/my"
               "interfaces/src/my/company"
               "interfaces/src/my/company/comp_2"
               "interfaces/src/my/company/comp_2/interface.clj"
               "interfaces/src/my/company/ifc_1"
               "interfaces/src/my/company/ifc_1/interface.clj"
               "logo.png"
               "project.clj"
               "systems"
               "systems/sys-1"
               "systems/sys-1/Readme.md"
               "systems/sys-1/build.sh"
               "systems/sys-1/project.clj"
               "systems/sys-1/resources"
               "systems/sys-1/resources/.keep"
               "systems/sys-1/resources/base-1"
               "systems/sys-1/resources/base-1/.keep"
               "systems/sys-1/resources/comp-1"
               "systems/sys-1/resources/comp-1/.keep"
               "systems/sys-1/sources"
               "systems/sys-1/sources/src"
               "systems/sys-1/sources/src-base-1"
               "systems/sys-1/sources/src-base-1/my"
               "systems/sys-1/sources/src-base-1/my/company"
               "systems/sys-1/sources/src-base-1/my/company/base_1"
               "systems/sys-1/sources/src-base-1/my/company/base_1/core.clj"
               "systems/sys-1/sources/src/my"
               "systems/sys-1/sources/src/my/company"
               "systems/sys-1/sources/src/my/company/comp_1"
               "systems/sys-1/sources/src/my/company/comp_1/core.clj"}
             (set (file/relative-paths ws-dir)))))))

(deftest polylith-remove-from--remove-component-from-system-without-namespace--component-removed
  (with-redefs [file/current-path (fn [] @helper/root-dir)]
    (let [ws-dir (str @helper/root-dir "/ws1")
          project (helper/settings ws-dir "")]
      (polylith/polylith nil "create" "w" "ws1" "-")
      (polylith/polylith project "create" "s" "sys-1" "base-1")
      (polylith/polylith project "create" "c" "comp-1" "ifc-1")
      (polylith/polylith project "create" "c" "comp-2")
      (polylith/polylith project "add" "comp-1" "sys-1")
      (polylith/polylith project "add" "comp-2" "sys-1")
      (polylith/polylith project "remove-from" "sys-1" "comp-2")

      (is (= #{".gitignore"
               ".polylith"
               ".polylith/time.local.edn"
               "Readme.md"
               "bases"
               "bases/base-1"
               "bases/base-1/Readme.md"
               "bases/base-1/project.clj"
               "bases/base-1/resources"
               "bases/base-1/resources/.keep"
               "bases/base-1/resources/base-1"
               "bases/base-1/resources/base-1/.keep"
               "bases/base-1/src"
               "bases/base-1/src/base_1"
               "bases/base-1/src/base_1/core.clj"
               "bases/base-1/test"
               "bases/base-1/test/base_1"
               "bases/base-1/test/base_1/core_test.clj"
               "components"
               "components/comp-1"
               "components/comp-1/Readme.md"
               "components/comp-1/project.clj"
               "components/comp-1/resources"
               "components/comp-1/resources/.keep"
               "components/comp-1/resources/comp-1"
               "components/comp-1/resources/comp-1/.keep"
               "components/comp-1/src"
               "components/comp-1/src/comp_1"
               "components/comp-1/src/comp_1/core.clj"
               "components/comp-1/src/ifc_1"
               "components/comp-1/src/ifc_1/interface.clj"
               "components/comp-1/test"
               "components/comp-1/test/comp_1"
               "components/comp-1/test/comp_1/core_test.clj"
               "components/comp-2"
               "components/comp-2/Readme.md"
               "components/comp-2/project.clj"
               "components/comp-2/resources"
               "components/comp-2/resources/.keep"
               "components/comp-2/resources/comp-2"
               "components/comp-2/resources/comp-2/.keep"
               "components/comp-2/src"
               "components/comp-2/src/comp_2"
               "components/comp-2/src/comp_2/core.clj"
               "components/comp-2/src/comp_2/interface.clj"
               "components/comp-2/test"
               "components/comp-2/test/comp_2"
               "components/comp-2/test/comp_2/core_test.clj"
               "environments"
               "environments/development"
               "environments/development/docs"
               "environments/development/docs/base-1-Readme.md"
               "environments/development/docs/comp-1-Readme.md"
               "environments/development/docs/comp-2-Readme.md"
               "environments/development/docs/sys-1-Readme.md"
               "environments/development/interfaces"
               "environments/development/interfaces/comp_2"
               "environments/development/interfaces/comp_2/interface.clj"
               "environments/development/interfaces/ifc_1"
               "environments/development/interfaces/ifc_1/interface.clj"
               "environments/development/project-files"
               "environments/development/project-files/bases"
               "environments/development/project-files/bases/base-1-project.clj"
               "environments/development/project-files/components"
               "environments/development/project-files/components/comp-1-project.clj"
               "environments/development/project-files/components/comp-2-project.clj"
               "environments/development/project-files/interfaces-project.clj"
               "environments/development/project-files/systems"
               "environments/development/project-files/systems/sys-1-project.clj"
               "environments/development/project-files/workspace-project.clj"
               "environments/development/project.clj"
               "environments/development/resources"
               "environments/development/resources/.keep"
               "environments/development/resources/base-1"
               "environments/development/resources/base-1/.keep"
               "environments/development/resources/comp-1"
               "environments/development/resources/comp-1/.keep"
               "environments/development/resources/comp-2"
               "environments/development/resources/comp-2/.keep"
               "environments/development/sources"
               "environments/development/sources/src"
               "environments/development/sources/src-base-1"
               "environments/development/sources/src-base-1/base_1"
               "environments/development/sources/src-base-1/base_1/core.clj"
               "environments/development/sources/src/comp_1"
               "environments/development/sources/src/comp_1/core.clj"
               "environments/development/sources/src/comp_2"
               "environments/development/sources/src/comp_2/core.clj"
               "environments/development/sources/src/comp_2/interface.clj"
               "environments/development/sources/src/ifc_1"
               "environments/development/sources/src/ifc_1/interface.clj"
               "environments/development/tests"
               "environments/development/tests/test"
               "environments/development/tests/test-base-1"
               "environments/development/tests/test-base-1/base_1"
               "environments/development/tests/test-base-1/base_1/core_test.clj"
               "environments/development/tests/test/comp_1"
               "environments/development/tests/test/comp_1/core_test.clj"
               "environments/development/tests/test/comp_2"
               "environments/development/tests/test/comp_2/core_test.clj"
               "interfaces"
               "interfaces/project.clj"
               "interfaces/src"
               "interfaces/src/comp_2"
               "interfaces/src/comp_2/interface.clj"
               "interfaces/src/ifc_1"
               "interfaces/src/ifc_1/interface.clj"
               "logo.png"
               "project.clj"
               "systems"
               "systems/sys-1"
               "systems/sys-1/Readme.md"
               "systems/sys-1/build.sh"
               "systems/sys-1/project.clj"
               "systems/sys-1/resources"
               "systems/sys-1/resources/.keep"
               "systems/sys-1/resources/base-1"
               "systems/sys-1/resources/base-1/.keep"
               "systems/sys-1/resources/comp-1"
               "systems/sys-1/resources/comp-1/.keep"
               "systems/sys-1/sources"
               "systems/sys-1/sources/src"
               "systems/sys-1/sources/src-base-1"
               "systems/sys-1/sources/src-base-1/base_1"
               "systems/sys-1/sources/src-base-1/base_1/core.clj"
               "systems/sys-1/sources/src/comp_1"
               "systems/sys-1/sources/src/comp_1/core.clj"}
             (set (file/relative-paths ws-dir)))))))
