(ns leiningen.polylith.cmd.help.changes)

(defn help []
  (println "  Show what has been changed since a specific point in time.")
  (println)
  (println "  lein polylith changes ENTITY PREFIX [ARG]")
  (println "    PREFIX = (omitted) -> Uses local.time")
  (println "             prefix    -> Uses given prefix with .time extension.")
  (println)
  (println "    ENTITY = i[nterface] -> Show changed interfaces")
  (println "             c[omponent] -> Show changed components")
  (println "             b[ase]      -> Show changed bases")
  (println "             s[ystem]    -> Show changed systems")
  (println "    ARG = (omitted) -> Since last successful build, stored in bookmark")
  (println "                       :last-successful-build in WS-ROOT/.polylith/local.time.")
  (println "          timestamp -> Since the given timestamp (milliseconds since 1970).")
  (println "          bookmark  -> Since the timestamp for the given bookmark in WS-ROOT/.polylith/local.time")
  (println)
  (println "  example:")
  (println "    lein polylith changes i")
  (println "    lein polylith changes c")
  (println "    lein polylith changes component")
  (println "    lein polylith changes b")
  (println "    lein polylith changes b local")
  (println "    lein polylith changes b remote")
  (println "    lein polylith changes s local 1523649477000")
  (println "    lein polylith changes s local mybookmark"))
