(ns leiningen.polylith.cmd.help.compile)

(defn help []
  (println "  Compile changes since a specific point in time.")
  (println)
  (println "  lein polylith compile [ARG]")
  (println "    ARG = (omitted) -> Since last successful build, stored in bookmark")
  (println "                       :last-successful-build in WS-ROOT/.polylith/time.edn.")
  (println "          timestamp -> Since the given timestamp (milliseconds since 1970).")
  (println "          bookmark  -> Since the timestamp for the given bookmark in WS-ROOT/.polylith/time.edn.")
  (println)
  (println "  example:")
  (println "    lein polylith compile")
  (println "    lein polylith compile 1523649477000")
  (println "    lein polylith compile mybookmark"))
