(ns leiningen.polylith.cmd.help.compile)

(defn help []
  (println "  Compile changes since a specific point in time.")
  (println)
  (println "  lein polylith compile [ARG]")
  (println "    ARG = (omitted) -> Since last successful build, stored in bookmark")
  (println "                       :last-successful-build in WS-ROOT/.polylith/time.edn")
  (println "                       or :last-successful-build in WS-ROOT/.polylith/git.edn")
  (println "                       if you have the CI variable set to something on the machine.")
  (println "          timestamp -> Since the given timestamp (milliseconds since 1970).")
  (println "          git-hash  -> Since the given git hash if the CI variable is set.")
  (println "          bookmark  -> Since the timestamp for the given bookmark in")
  (println "                       WS-ROOT/.polylith/time.edn or since the git hash")
  (println "                       for the given bookmark in WS-ROOT/.polylith/git.edn")
  (println "                       if the CI variable is set.")
  (println)
  (println "    SKIP = (omitted)  -> Compiles and tests")
  (println "           -sync-deps -> Skips dependency sync step")
  (println)
  (println "  'lein polylith compile 0' can be used to compile all files in the workspace")
  (println "  (or at least changes since 1970-01-01).")
  (println)
  (println "  example:")
  (println "    lein polylith compile")
  (println "    lein polylith compile -sync-deps")
  (println "    lein polylith compile 1523649477000")
  (println "    lein polylith compile 7d7fd132412aad0f8d3019edfccd1e9d92a5a8ae")
  (println "    lein polylith compile mybookmark")
  (println "    lein polylith compile mybookmark -sync-deps"))
