(ns leiningen.polylith.cmd.help.deps)

(defn help []
  (println "  List dependencies.")
  (println)
  (println "  lein polylith deps ARG")
  (println "    ARG = (omitted) -> list component dependencies")
  (println "          c         -> list component dependencies")
  (println "          i         -> list interface dependencies")
  (println "          f         -> list function dependencies")
  (println)
  (println "  Only active components, that are used in at least one")
  (println "  environment or system, are shown when listing components.")
  (println)
  (println "  To work correctly, :require with a corresponding :as alias")
  (println "  must be used to specify dependencies in each namespace, e.g.:")
  (println "    (ns my.namespace.core")
  (println "      (:require [my.namespace.user.interface :as user]")
  (println "                [my.namespace.email.interface :as email]))")
  (println)
  (println "  example:")
  (println "    lein polylith deps i")
  (println "    lein polylith deps f"))
