(ns leiningen.polylith.cmd.help.prompt)

(defn help []
  (println "  Starts a prompt for current workspace.")
  (println)
  (println "  Allows faster execution of all the commands from any directory.")
  (println)
  (println "  The Unix commands 'cd', 'ls', 'cat', 'pwd' and 'open' are also supported.")
  (println "  Executing 'cd' with no arguments will take you to the workspace root.")
  (println "  It's only possible to go to a directory within the workspace.")
  (println)
  (println "  Type 'exit' or 'quit' to exit the prompt.")
  (println)
  (println "  examples:")
  (println "    lein polylith prompt"))
