(ns leiningen.polylith.cmd.help.run)

(defn help []
  (println "  Executes the standalone jar file that was created")
  (println "  by the 'build' command, for specified system.")
  (println)
  (println "  lein polylith run SYSTEM [ARGS]")
  (println "    SYSTEM = Name of the system.")
  (println "    ARGS   = Arguments used when executing the jar file.")
  (println)
  (println "  The command 'run mysystem x' will execute the command:")
  (println "    java -jar WS-ROOT/systems/mysystem/target/mysystem-0.1-standalone.jar x")
  (println)
  (println "  ...where \"x\" is passed to its \"-main [& args]\" function.")
  (println)
  (println "  example:")
  (println "    lein polylith run mysystem")
  (println "    lein polylith run mysystem arg1")
  (println "    lein polylith run mysystem arg1 arg2"))
