(ns leiningen.polylith.cmd.help.success)

(defn help []
  (println "  Depending on whether the environment variable CI is set or not, it does:")
  (println)
  (println "    If CI is not set (when executed from the local development environment):")
  (println "      Sets the BOOKMARK in WS-ROOT/.polylith/time.edn to current time")
  (println "      in milliseconds.")
  (println)
  (println "    If CI is set (when executed from the continuous integration server):")
  (println "      Sets the BOOKMARK in WS-ROOT/.polylith/git.edn to current Git SHA1.")
  (println)
  (println "  lein polylith success [BOOKMARK]")
  (println "    BOOKMARK = (omitted) -> last-successful-build")
  (println "               name of the bookmark")
  (println)
  (println "  examples:")
  (println "    lein polylith success")
  (println "    lein polylith success mybookmark"))
